name: Build UABEA Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: msbuild UABEAutomation.sln /restore /p:Configuration=Release
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: uabea-windows
        path: UABEAutomation/bin/Release/net6.0
